[package]
name = "rendering"
version = "0.1.0"
authors = ["doomguy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
# gl_loader = "0.1.2"
sys = { path = "../sys" }